modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL v3"
[[mods]]
modId="prairies"
version="1.0.0"
displayName="Prairies"
credits="${mod_authors}"
description='''
${mod_description}
'''
[[dependencies.worldofwonder]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.worldofwonder]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    